[package]
name = "axum-otel"
version = "0.29.1"
edition = "2021"
description = "OpenTelemetry tracing for axum."
license = "MIT/Apache-2.0"
repository = "https://github.com/iamnivekx/axum-otel"
documentation = "https://docs.rs/axum-otel/"
readme = "README.md"
authors = ["nivek <h49987180@gmail.com>"]

[dependencies]
tracing = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
tracing-opentelemetry = { workspace = true }
axum = { workspace = true }
pin-project-lite = { workspace = true }
uuid = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

[dev-dependencies]
axum = { version = "0.8", default-features = false, features = ["macros"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
