[package]
name = "axum-otel-demo"
version = "0.1.0"
authors = ["nivek <h49987180@gmail.com>"]
edition = "2021"

license = "MIT/Apache-2.0"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
axum-otel = { path = "../../crates/axum-otel" }

anyhow = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tower = "0.5"
tower-http = "0.6"
opentelemetry = "0.29"
opentelemetry-otlp = { version = "0.29", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.29", features = ["rt-tokio-current-thread"] }
opentelemetry-semantic-conventions = "0.29"
tokio = { version = "1.39", features = ["full"] }
tracing = "0.1"
tracing-bunyan-formatter = "0.3"
tracing-opentelemetry = "0.30"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
